config/routes.rb
Rails.application.routes.draw do
  resources :candidates, only: [:new, :create]
  resources :voters, only: [:new, :create, :update]

  get "vote" => "candidates#vote"
  get "results" => "candidates#results"

  get "start" => "voters#new"
  get "sign_out" => "application#sign_out"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root to: "candidates#results"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  has_many :voters
end

app/models/voter.rb
class Voter < ApplicationRecord
  belongs_to :candidate, optional: true

  validates :email, uniqueness: true, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :session_expired

  def session_expired
    if session[:expires_at].nil? || session[:expires_at] < Time.now
      reset_session
      redirect_to start_path, error: "Your session expired, start again"
    end
  end

  def current_voter
    Voter.find(session[:current_voter_id])
  end

  def sign_out
    reset_session
    redirect_to results_path
  end

  def reset_session
    session[:current_voter_id] = nil
    session[:expires_at] = nil
  end
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  skip_before_action :session_expired, only: :results

  # GET /candidates/new
  def new
    @candidate = Candidate.new
  end

  def vote
    @candidates = Candidate.all
    @candidate = Candidate.new
    @voter = current_voter
    if @voter.nil?
      redirect_to start
    end
  end

  def results
    @candidates = Candidate.order(:name)
  end

  # POST /candidates or /candidates.json
  def create
    @candidate = Candidate.create(candidate_params)

    current_voter.update(candidate_id: @candidate.id)
    sign_out
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidate
      @candidate = Candidate.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def candidate_params
      params.require(:candidate).permit(:name)
    end
end

app/controllers/voters_controller.rb
class VotersController < ApplicationController
  before_action :set_voter, only: %i[ update ]
  skip_before_action :session_expired

  # GET /voters/new
  def new
    @voter = Voter.new
  end

  # POST /voters or /voters.json
  def create
    @voter = Voter.find_or_create_by(email: voter_params[:email])
    session[:current_voter_id] = @voter.id
    session[:expires_at] = 5.minutes.from_now

    respond_to do |format|
      if @voter.update(voter_params)
        format.html { redirect_to vote_path}
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /voters/1 or /voters/1.json
  def update
    @voter.update(voter_params)
    sign_out
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_voter
    @voter = Voter.find(session[:current_voter_id])
  end

  # Only allow a list of trusted parameters through.
  def voter_params
    params.require(:voter).permit(:email, :zip_code, :candidate_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/voters_helper.rb
module VotersHelper
end

app/views/candidates/results.html.erb
<p style="color: green"><%= notice %></p>

<h1>Election results</h1>

<table id="candidates">
  <% @candidates.each do |candidate| %>
    <tr>
      <td> <%= candidate.name %> </td>
      <td> <%= candidate.voters.length %> </td>
    </tr>
  <% end %>
</table>

app/views/candidates/vote.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cast your vote today!</h1>

<%= form_for(@voter) do |f| %>
  <% @candidates.each do |candidate| %>
    <%= f.radio_button :candidate_id, candidate.id %>
    <%= f.label :candidate_id, candidate.name %>
    <br />
  <% end %>
  <div>
    <%= f.submit "Vote" %>
  </div>
<% end %>


<% if @candidates.count < 10 %>
<hr>
  Or, add a new candidate:

  <%= form_for(@candidate) do |f| %>
    <div>
      <%= f.text_field :name %>
      <%= f.submit  "Vote" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VotingMachine</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
  </head>

  <body>
    <div>VOTE.WEBSITE</div>
    <% if session[:current_voter_id].present? %>
      <div> Signed in as <%=Voter.find(session[:current_voter_id]).email %> </div>
      <div> Your session will expire in <%= Time.at(Time.parse(session[:expires_at]) - Time.now).utc.strftime("%M:%S") %> </div>
      <%= link_to "Sign out", sign_out_url %>
    <% else %>
      <%= link_to "Vote", start_path %>
    <% end %>
    <%= link_to "Results", results_path %>
    <%= yield %>
  </body>
</html>

app/views/voters/new.html.erb
<h1>Check In</h1>

<%= form_with(model: @voter) do |form| %>
  <% if @voter.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@voter.errors.count, "error") %> prohibited this voter from being saved:</h2>

      <ul>
        <% @voter.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :zip_code, style: "display: block" %>
    <%= form.text_field :zip_code %>
  </div>

  <div>
    <%= form.submit "Continue" %>
  </div>
<% end %>